services:
  mysql:
    image: mysql:8.0
    container_name: school-platform-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: devpass
      MYSQL_DATABASE: school_platform_dev
    command: ["--default-authentication-plugin=mysql_native_password"]
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data:

